services:

  server:
    container_name: oc_lettings_site
    build:
      context: .
      target: prod
    restart: no
    # ports:
    #   - 8000:8000
    volumes:
      - sqlite_data:/var/lib/sqlite/data

volumes:
  sqlite_data:
    driver: local
