services:

  oc_lettings_app:
    container_name: server
    build:
      context: .
      target: dev
    image: oc_lettings_app:lastest
    restart: no
    ports:
      - 8000:8000
    volumes:
      - sqlite_data:/var/lib/sqlite/data
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  sqlite_data:
    driver: local
