services:

  oc_lettings_app:
    container_name: server
    build: .
    image: oc_lettings_apps:lastest
    restart: no
    ports:
      - 8000:8000
    volumes:
      - sqlite_data:/var/lib/sqlite/data

volumes:
  sqlite_data:
    driver: local
