services:

  server:
    container_name: oc_lettings_site
    build:
      context: .
      dockerfile: docker/dockerfile
      target: dev
    restart: no
    ports:
      - 8000:8000
    volumes:
      - sqlite_data:/var/lib/sqlite/data
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  sqlite_data:
    driver: local
