# Generated by Django 3.0 on 2024-09-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0002_profile_nickname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="nickname",
        ),
    ]
