# Generated by Django 3.0 on 2024-09-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='test_filed',
            field=models.CharField(default='aa', max_length=2),
            preserve_default=False,
        ),
    ]
