# Generated by Django 3.0 on 2024-09-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting_app', '0002_address_test_filed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='test_filed',
        ),
    ]
