# Generated by Django 3.0 on 2024-10-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting_app', '0003_remove_address_test_filed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
